if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
ZSH_THEME="powerlevel10k/powerlevel10k"

# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=( 
  archlinux
	python
	extract
	sudo
	git 
	zsh-syntax-highlighting 
	zsh-autosuggestions 
)

source $ZSH/oh-my-zsh.sh

# User configuration

# Aliases
alias ls='clear && lsd'
alias sl="ls"
alias ks="ls"
alias lss="ls"

alias celar=clear
alias ckear=clear
alias vlear=clear
alias clekar=clear
alias lcear=clear
alias cleaer=clear
alias claer=clear
alias cealr=clear
alias cear=clear
alias celaer=clear
alias cekar=clear
alias caelr=clear

alias xxx="nvim ~/.zshrc"
alias sss="source ~/.zshrc"

alias dea='deactivate'
alias nvim='~/.local/bin/lvim'
alias vim='~/.local/bin/lvim'
alias vi='~/.local/bin/lvim'


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/.local/bin/:$PATH"

# Mycustom automations Scripts
export PATH="$HOME/.Personal/Scripts/:$PATH"
